/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { TransactionRequest } from 'ethers';

type BaseOverrides = Omit<TransactionRequest, 'to' | 'data'>;

type NonPayableOverrides = Omit<
  BaseOverrides,
  'value' | 'blockTag' | 'enableCcipRead'
>;

type PayableOverrides = Omit<BaseOverrides, 'blockTag' | 'enableCcipRead'>;

type ViewOverrides = Omit<TransactionRequest, 'to' | 'data'>;

export type Overrides<S extends StateMutability> = S extends 'nonpayable'
  ? NonPayableOverrides
  : S extends 'payable'
    ? PayableOverrides
    : ViewOverrides;

export type StateMutability = 'nonpayable' | 'payable' | 'view';
