/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { BaseContract, BytesLike, ContractRunner } from 'ethers';
import { TypedContractMethod } from './typed-contract-method.interface';

export interface IMinArbitraryDataArtifact extends BaseContract {
  connect(runner?: ContractRunner | null): IMinArbitraryDataArtifact;

  exec: TypedContractMethod<[data: BytesLike[]], [string], 'nonpayable'>;

  getExecDescriptor: TypedContractMethod<
    [],
    [
      [string[], string[], string] & {
        argsNames: string[];
        argsTypes: string[];
        returnType: string;
      },
    ],
    'view'
  >;

  getInitDescriptor: TypedContractMethod<
    [],
    [[string[], string[]] & { argsNames: string[]; argsTypes: string[] }],
    'view'
  >;

  init: TypedContractMethod<[data: BytesLike], [void], 'nonpayable'>;
}
