export const DEVELOPMENT_CHAIN_ID = 'DEVELOPMENT_CHAIN_ID';
export const DEVELOPMENT_RPC = 'DEVELOPMENT_RPC';
export const HARDHAT_MINING_AUTO = 'HARDHAT_MINING_AUTO';
export const HARDHAT_MINING_INTERVAL = 'HARDHAT_MINING_INTERVAL';

export const INFURA_KEY = 'INFURA_KEY';
export const ALCHEMY_KEY = 'ALCHEMY_KEY';

export const IS_NETWORK_FORKING_ENABLED = 'IS_NETWORK_WORK_ENABLED';

export const MNEMONIC = 'MNEMONIC';
export const POLYGONSCAN_API_KEY = 'POLYGONSCAN_API_KEY';
export const REPORT_GAS = 'REPORT_GAS';
